SELECT TOP 1 * FROM FITNESS.TBL_ALUNO ORDER BY ID DESC 

SELECT * FROM COMERCIAL.TBL_CONTRATO WHERE ALUNO_ID = 381271

SELECT A.* 
FROM FITNESS.TBL_ALUNO AS A
INNER JOIN COMERCIAL.TBL_CONTRATO AS B
	ON A.[ULT_CONTRATO_ID] = B.[ID]
WHERE (SELECT COUNT(*) FROM COMERCIAL.TBL_CONTRATO AS B1 WHERE B1.ALUNO_ID  = A.ID ) = 1
	AND B.[DATA_CADASTRO] BETWEEN '2019-06-19' AND '2019-06-30'
	AND A.[AUDITORIA] NOT LIKE '%RENOVAR%'
	AND A.[AUDITORIA] NOT LIKE '%CANCELAR%'


	SELECT A.*  FROM FITNESS.TBL_ALUNO AS A  INNER JOIN COMERCIAL.TBL_CONTRATO AS B  ON A.[ULT_CONTRATO_ID] = B.[ID]  WHERE(SELECT COUNT(*) FROM COMERCIAL.TBL_CONTRATO AS B1 WHERE B1.ALUNO_ID = A.ID) = 1  AND B.[DATA_CADASTRO] BETWEEN '2019-06-19' AND '2019-06-30'  AND A.[AUDITORIA] NOT LIKE '%RENOVAR%'  AND A.[AUDITORIA] NOT LIKE '%CANCELAR%' 
