// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using UploadImgur.ImgurJsonJsonTypes;

namespace UploadImgur.ImgurJsonJsonTypes
{

    public class Error
    {

        [JsonProperty("code")]
        public int Code { get; set; }

        [JsonProperty("message")]
        public string Message { get; set; }

        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("exception")]
        public object[] Exception { get; set; }
    }

}
